# Generated by Django 6.0.2 on 2026-03-29 13:35

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ObjectDoesNotExist


def crear_usuarios_prueba(apps, schema_editor):
    """
    Crea usuarios de prueba organizados por grupos
    """

    Group = apps.get_model('auth', 'Group')
    Usuario = apps.get_model('users', 'Usuario')

    PASSWORD = 'Prueba123!'  # ⚠️ Cambiar en producción

    # ========= 1. VALIDAR GRUPOS =========
    grupos_nombres = [
        'Administrador',
        'Gerente General',
        'Gerente de Habitaciones',
        'Gerente de Comidas y Bebidas',
        'Asistente Administrativo'
    ]

    grupos = {}

    for nombre in grupos_nombres:
        try:
            grupos[nombre] = Group.objects.get(name=nombre)
        except Group.DoesNotExist:
            raise ObjectDoesNotExist(
                f"El grupo '{nombre}' no existe. Ejecuta primero la migración 0002."
            )

    # ========= 2. DEFINICIÓN DE USUARIOS =========
    usuarios_data = {
        'Administrador': [
            {
                'username': 'admin_principal',
                'email': 'admin@lajelegante.com',
                'first_name': 'Admin',
                'last_name': 'Principal'
            },
            {
                'username': 'admin_backup',
                'email': 'admin2@lajelegante.com',
                'first_name': 'Admin',
                'last_name': 'Backup'
            },
            {
                'username': 'admin_seguridad',
                'email': 'admin3@lajelegante.com',
                'first_name': 'Admin',
                'last_name': 'Seguridad'
            },
            {
                'username': 'jeremy_duarte',
                'email': 'jeremydamian.db@gmail.com',
                'first_name': 'Jeremy',
                'last_name': 'Duarte'
            }
        ],
        'Gerente General': [
            {
                'username': 'gerente_general_1',
                'email': 'gerente1@lajelegante.com',
                'first_name': 'Carlos',
                'last_name': 'López'
            },
            {
                'username': 'gerente_general_2',
                'email': 'gerente2@lajelegante.com',
                'first_name': 'María',
                'last_name': 'García'
            },
            {
                'username': 'gerente_general_3',
                'email': 'gerente3@lajelegante.com',
                'first_name': 'Juan',
                'last_name': 'Rodríguez'
            }
        ],
        'Gerente de Habitaciones': [
            {
                'username': 'gerente_hab_1',
                'email': 'ghabitaciones1@lajelegante.com',
                'first_name': 'Ana',
                'last_name': 'Martínez'
            },
            {
                'username': 'gerente_hab_2',
                'email': 'ghabitaciones2@lajelegante.com',
                'first_name': 'Luis',
                'last_name': 'Sánchez'
            },
            {
                'username': 'gerente_hab_3',
                'email': 'ghabitaciones3@lajelegante.com',
                'first_name': 'Carmen',
                'last_name': 'Pérez'
            }
        ],
        'Gerente de Comidas y Bebidas': [
            {
                'username': 'gerente_cyb_1',
                'email': 'gcomidas1@lajelegante.com',
                'first_name': 'Roberto',
                'last_name': 'Gómez'
            },
            {
                'username': 'gerente_cyb_2',
                'email': 'gcomidas2@lajelegante.com',
                'first_name': 'Sofía',
                'last_name': 'Fernández'
            },
            {
                'username': 'gerente_cyb_3',
                'email': 'gcomidas3@lajelegante.com',
                'first_name': 'Diego',
                'last_name': 'Torres'
            }
        ],
        'Asistente Administrativo': [
            {
                'username': 'asistente_1',
                'email': 'asistente1@lajelegante.com',
                'first_name': 'Laura',
                'last_name': 'Ramírez'
            },
            {
                'username': 'asistente_2',
                'email': 'asistente2@lajelegante.com',
                'first_name': 'Pedro',
                'last_name': 'Castro'
            },
            {
                'username': 'asistente_3',
                'email': 'asistente3@lajelegante.com',
                'first_name': 'Elena',
                'last_name': 'Morales'
            }
        ]
    }

    # ========= 3. CREAR USUARIOS =========
    for grupo_nombre, usuarios_lista in usuarios_data.items():
        grupo = grupos[grupo_nombre]

        for user_data in usuarios_lista:
            usuario, created = Usuario.objects.get_or_create(
                username=user_data['username'],
                defaults={
                    'email': user_data['email'],
                    'first_name': user_data['first_name'],
                    'last_name': user_data['last_name'],
                    'password': make_password(PASSWORD),
                    'is_active': True,
                    'is_staff': grupo_nombre == 'Administrador',
                    'is_superuser': user_data['username'] == 'admin_principal',
                }
            )

            # ✅ Asegurar password consistente
            if not created:
                usuario.password = make_password(PASSWORD)

            # ✅ Asignar SOLO el grupo correcto
            usuario.groups.set([grupo])

            # ✅ Configuración especial Jeremy
            if user_data['username'] == 'jeremy_duarte':
                usuario.is_staff = True
                usuario.is_superuser = True

            usuario.save()


def eliminar_usuarios_prueba(apps, schema_editor):
    """
    Rollback: elimina los usuarios de prueba creados
    """
    Usuario = apps.get_model('users', 'Usuario')

    usuarios_a_eliminar = [
        'admin_principal', 'admin_backup', 'admin_seguridad', 'jeremy_duarte',
        'gerente_general_1', 'gerente_general_2', 'gerente_general_3',
        'gerente_hab_1', 'gerente_hab_2', 'gerente_hab_3',
        'gerente_cyb_1', 'gerente_cyb_2', 'gerente_cyb_3',
        'asistente_1', 'asistente_2', 'asistente_3'
    ]

    Usuario.objects.filter(username__in=usuarios_a_eliminar).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_groups_and_permissions'),
    ]

    operations = [
        migrations.RunPython(crear_usuarios_prueba, eliminar_usuarios_prueba),
    ]