# Generated by Django 6.0.2 on 2026-03-26 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_habitacion', models.PositiveIntegerField(unique=True, verbose_name='número de habitación')),
                ('estado_habitacion', models.CharField(choices=[('EN_SERVICIO', 'en servicio'), ('MANTENIMIENTO', 'mantenimiento'), ('OCUPADA', 'ocupada')], default='EN_SERVICIO', max_length=20, verbose_name='estado de la habitación')),
            ],
            options={
                'verbose_name': 'habitación',
                'verbose_name_plural': 'habitaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre_tipo', models.CharField(choices=[('FAMILIAR', 'familiar'), ('PAREJA', 'pareja'), ('BASICA', 'basica'), ('ESPECIAL', 'especial')], max_length=20, verbose_name='nombre del tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('capacidad_maxima', models.PositiveIntegerField(verbose_name='capacidad máxima')),
            ],
            options={
                'verbose_name': 'tipo de habitación',
                'verbose_name_plural': 'tipos de habitaciones',
            },
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_habitacion', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'reserva de habitación',
                'verbose_name_plural': 'reservas de habitaciones',
            },
        ),
        migrations.CreateModel(
            name='DetallesReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('cantidad_personas', models.PositiveIntegerField(verbose_name='cantidad de personas')),
                ('precio_por_noche', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='precio por noche')),
                ('cantidad_noches', models.PositiveIntegerField(editable=False, verbose_name='cantidad de noches')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='descuento adicional')),
                ('recargo_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='recargo adicional')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='precio total')),
                ('observacion', models.TextField(blank=True)),
                ('tarifa_aplicada', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.tarifa', verbose_name='tarifa aplicada')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_reserva', to='rooms.habitacion')),
                ('reserva_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rooms.reservahabitacion')),
            ],
            options={
                'verbose_name': 'detalle de reserva',
                'verbose_name_plural': 'detalles de reservas',
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='rooms.tipohabitacion', verbose_name='tipo de habitación'),
        ),
    ]
