# Generated by Django 6.0.2 on 2026-02-16 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_habitacion', models.PositiveIntegerField(unique=True)),
                ('estado_habitacion', models.CharField(choices=[('EN_SERVICIO', 'en servicio'), ('MANTENIMIENTO', 'mantenimiento'), ('OCUPADA', 'ocupada')], default='EN_SERVICIO', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre_tipo', models.CharField(choices=[('FAMILIAR', 'familiar'), ('PAREJA', 'pareja'), ('BASICA', 'basica'), ('ESPECIAL', 'especial')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_maxima', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('cantidad_noches', models.PositiveIntegerField()),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('recargo_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_reserva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_reserva', to='rooms.habitacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cliente_id', models.PositiveIntegerField()),
                ('detalle_reserva_habitacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='rooms.detallesreservahabitacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='rooms.tipohabitacion'),
        ),
    ]
