# Generated by Django 6.0.2 on 2026-03-28 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre_tipo', models.CharField(choices=[('FAMILIAR', 'familiar'), ('PAREJA', 'pareja'), ('BASICA', 'basica'), ('ESPECIAL', 'especial')], max_length=20, verbose_name='nombre del tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('capacidad_maxima', models.PositiveIntegerField(verbose_name='capacidad máxima')),
            ],
            options={
                'verbose_name': 'tipo de habitación',
                'verbose_name_plural': 'tipos de habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_habitacion', models.PositiveIntegerField(unique=True, verbose_name='número de habitación')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'disponible'), ('MANTENIMIENTO', 'mantenimiento'), ('OCUPADA', 'ocupada'), ('RESERVADA', 'reservada')], default='DISPONIBLE', max_length=20, verbose_name='estado de la habitación')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='rooms.tipohabitacion', verbose_name='tipo de habitación')),
            ],
            options={
                'verbose_name': 'habitación',
                'verbose_name_plural': 'habitaciones',
            },
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='estado reserva')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(verbose_name='fecha de entrada')),
                ('fecha_fin', models.DateField(verbose_name='fecha de salida')),
                ('cantidad_personas', models.PositiveIntegerField(verbose_name='cantidad de personas')),
                ('cantidad_noches', models.PositiveIntegerField(default=0, editable=False)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='rooms.habitacion', verbose_name='habitación')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.reserva')),
                ('tarifa_aplicada', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.tarifa')),
            ],
            options={
                'verbose_name': 'reserva de habitación',
                'verbose_name_plural': 'reservas de habitaciones',
                'indexes': [models.Index(fields=['fecha_inicio', 'fecha_fin'], name='rooms_reser_fecha_i_1e6f22_idx'), models.Index(fields=['habitacion', 'fecha_inicio', 'fecha_fin'], name='rooms_reser_habitac_233f81_idx')],
            },
        ),
    ]
