# Generated by Django 6.0.2 on 2026-03-12 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservahabitacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_habitacion', to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='detallesreservahabitacion',
            name='reserva_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rooms.reservahabitacion'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='rooms.tipohabitacion', verbose_name='tipo de habitación'),
        ),
    ]
