sonar.projectKey=sena-desarrollo-de-software_ljelegante-python
sonar.organization=sena-desarrollo-de-software


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=LaJElegante-Python
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
sonar.python.version=3.12,3.14
sonar.exclusions=**/migrations/**,**/tests/**,**/venv/**,**/__pycache__/**,**/img/**,**/images/**,**/*.pyc,**/static/vendor/**,**/static/fonts/**,**/static/img/**,**/static/img/icons/**,**/static/images/**,**/static/images/icons/**,**/static/css/fonts**
sonar.coverage.exclusions=**/settings.py,**/wsgi.py,**/asgi.py,**/manage.py,**/urls.py,**/apps.py,**/migrations/**,**/tests.py,**/tests/**,**/__init__.py