# Generated by Django 6.0.2 on 2026-03-26 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('imagen_pequena', models.ImageField(help_text='Tamaño: 300x85px - Para el navbar', upload_to='promociones/navbar/', verbose_name='imagen pequeña')),
                ('imagen_grande', models.ImageField(help_text='Formato 3:4 - Para página de promociones', upload_to='promociones/landingpage/', verbose_name='imagen grande')),
                ('tipo', models.CharField(choices=[('NAVBAR', 'Solo navbar (300x85px)'), ('PAGINA', 'Solo página completa'), ('AMBOS', 'Ambos formatos')], default='AMBOS', max_length=10, verbose_name='mostrar en')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20, verbose_name='estado')),
                ('orden_navbar', models.PositiveIntegerField(blank=True, help_text='Valor único. Dejar vacío si no va en navbar', null=True, unique=True, verbose_name='orden en navbar (1-4)')),
                ('fecha_inicio', models.DateTimeField(verbose_name='publicar desde')),
                ('fecha_fin', models.DateTimeField(verbose_name='publicar hasta')),
            ],
            options={
                'verbose_name': 'promoción',
                'verbose_name_plural': 'promociones',
                'ordering': ['orden_navbar', '-fecha_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('orden_navbar__gte', 1), ('orden_navbar__lte', 4)), ('orden_navbar__isnull', True), _connector='OR'), name='orden_navbar_rango')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
    ]
