# Generated by Django 6.0.2 on 2026-03-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('INACTIVA', 'Inactiva')], default='VIGENTE', max_length=10, verbose_name='estado')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio base (sin impuestos)')),
                ('precio_final', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='precio final (con impuestos)')),
            ],
            options={
                'verbose_name': 'tarifa',
                'verbose_name_plural': 'tarifas',
            },
        ),
        migrations.CreateModel(
            name='TarifaImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'impuesto de tarifa',
                'verbose_name_plural': 'impuestos de tarifa',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=50, verbose_name='nombre de temporada')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('porcentaje_modificador', models.IntegerField(default=0, help_text='Ej: 20 para +20%, -10 para -10%', verbose_name='ajuste de precio (%)')),
                ('modificador_precio', models.DecimalField(decimal_places=2, default=1.0, editable=False, max_digits=5, verbose_name='modificador (decimal)')),
            ],
            options={
                'verbose_name': 'temporada',
                'verbose_name_plural': 'temporadas',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre del impuesto')),
                ('tipo', models.CharField(choices=[('IVA', 'IVA (19%)'), ('ICA', 'ICA (Industria y Comercio)'), ('TIMBRE', 'Impuesto de Timbre (1.5%)'), ('PROPINA', 'Propina (voluntaria)'), ('CONSUMO', 'Impuesto al Consumo')], max_length=20, verbose_name='tipo de impuesto')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='porcentaje (%)')),
                ('aplica_a', models.CharField(choices=[('HABITACION', 'Solo habitación'), ('RESTAURANTE', 'Solo restaurante'), ('SERVICIOS', 'Servicios adicionales'), ('TODOS', 'Todos los servicios')], default='TODOS', max_length=20, verbose_name='aplica a')),
                ('es_obligatorio', models.BooleanField(default=True, verbose_name='es obligatorio')),
                ('aplica_extranjeros', models.BooleanField(default=True, verbose_name='aplica a extranjeros')),
                ('requiere_informacion_adicional', models.BooleanField(default=False, verbose_name='requiere texto informativo')),
                ('texto_informativo', models.TextField(blank=True, help_text='Ej: Texto obligatorio para propina según Circular 2 de 2012', verbose_name='texto informativo')),
                ('fecha_vigencia_inicio', models.DateField(verbose_name='fecha de inicio de vigencia')),
                ('fecha_vigencia_fin', models.DateField(blank=True, null=True, verbose_name='fecha de fin de vigencia')),
            ],
            options={
                'verbose_name': 'impuesto',
                'verbose_name_plural': 'impuestos',
                'ordering': ['tipo', 'fecha_vigencia_inicio'],
                'indexes': [models.Index(fields=['tipo', 'fecha_vigencia_inicio'], name='finance_imp_tipo_ef674a_idx')],
            },
        ),
    ]
