# Generated by Django 6.0.2 on 2026-03-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='tipo_habitacion',
            field=models.ForeignKey(db_column='id_tipo_habitacion', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='rooms.tipohabitacion', verbose_name='tipo de habitación'),
        ),
        migrations.AddField(
            model_name='tarifaimpuesto',
            name='impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.impuesto', verbose_name='impuesto'),
        ),
        migrations.AddField(
            model_name='tarifaimpuesto',
            name='tarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tarifa', verbose_name='tarifa'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='impuestos',
            field=models.ManyToManyField(blank=True, related_name='tarifas_aplicadas', through='finance.TarifaImpuesto', to='finance.impuesto', verbose_name='impuestos aplicables'),
        ),
        migrations.AlterUniqueTogether(
            name='temporada',
            unique_together={('nombre', 'fecha_inicio', 'fecha_fin')},
        ),
        migrations.AddField(
            model_name='tarifa',
            name='temporada',
            field=models.ForeignKey(db_column='id_temporada', on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='finance.temporada', verbose_name='temporada'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifaimpuesto',
            unique_together={('tarifa', 'impuesto')},
        ),
        migrations.AddIndex(
            model_name='tarifa',
            index=models.Index(fields=['estado', 'tipo_habitacion', 'temporada'], name='finance_tar_estado_fd8913_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifa',
            unique_together={('tipo_habitacion', 'temporada')},
        ),
    ]
