# Generated by Django 6.0.2 on 2026-02-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_mesa', models.SmallIntegerField()),
                ('capacidad', models.SmallIntegerField()),
                ('zona', models.CharField(max_length=50)),
                ('ubicacion_detalle', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cliente_id', models.PositiveIntegerField()),
                ('hora_reserva', models.TimeField()),
                ('numero_personas', models.SmallIntegerField()),
                ('estado_reserva', models.CharField(choices=[('PENDIENTE', 'pendiente'), ('CONFIRMADA', 'confirmada'), ('CANCELADA', 'cancelada')], default='PENDIENTE', max_length=20)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='restaurant.mesa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
