# Generated by Django 6.0.2 on 2026-04-06 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('turno', models.CharField(choices=[('MAÑANA', 'Desayuno'), ('TARDE', 'Almuerzo'), ('NOCHE', 'Cena')], max_length=10, unique=True, verbose_name='Franja Horaria')),
                ('hora_inicio', models.TimeField(verbose_name='Inicio del horario')),
                ('hora_fin', models.TimeField(verbose_name='Fin del horario')),
                ('capacidad_maxima', models.PositiveIntegerField(default=50, verbose_name='Capacidad maxima de esta franja horaria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuración de horario',
                'verbose_name_plural': 'conguración de horarios',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('quorum', models.PositiveIntegerField(default=0, verbose_name='Personas reservadas')),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, help_text='Sobreescribe capacidad maxima de los horarios (dejar vacio si no es necesario)', null=True, verbose_name='Capacidad maxima')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='restaurant.horario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
            },
        ),
        migrations.CreateModel(
            name='ReservaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='estado reserva')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_restaurantes', to='core.reserva')),
                ('tarifa_aplicada', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.tarifa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='restaurant.turno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['turno', 'capacidad_maxima'], name='restaurant__turno_3d3ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha', 'horario', 'capacidad_maxima'], name='restaurant__fecha_ba5c21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('fecha', 'horario')},
        ),
    ]
