# Generated by Django 6.0.2 on 2026-03-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_mesa', models.SmallIntegerField(verbose_name='número de mesa')),
                ('capacidad', models.SmallIntegerField(verbose_name='capacidad de personas')),
                ('zona', models.CharField(max_length=50, verbose_name='zona del restaurante')),
                ('ubicacion_detalle', models.CharField(max_length=150, verbose_name='ubicación detallada')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['zona', 'numero_mesa'],
                'unique_together': {('numero_mesa', 'zona')},
            },
        ),
        migrations.CreateModel(
            name='ReservaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hora_reserva', models.TimeField(verbose_name='hora de la reserva')),
                ('numero_personas', models.SmallIntegerField(verbose_name='número de personas')),
                ('estado_reserva', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='estado de la reserva')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='restaurant.mesa', verbose_name='mesa asignada')),
            ],
            options={
                'verbose_name': 'reserva de restaurante',
                'verbose_name_plural': 'reservas de restaurante',
                'ordering': ['-created_at', 'hora_reserva'],
            },
        ),
    ]
