# Generated by Django 6.0.2 on 2026-03-12 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservarestaurante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_restaurante', to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
        migrations.AddIndex(
            model_name='reservarestaurante',
            index=models.Index(fields=['estado_reserva', 'hora_reserva'], name='restaurant__estado__d19d56_idx'),
        ),
    ]
